heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance
parameters:
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      name: vm5888
      image: { get_param: image_id }
      flavor: m1.tiny
      networks: [{ network : ce5dbaab-9de3-4288-b983-54296a55219d }]
