
#jobs to be created in Jenkins will have value = 1
GERRIT_TRIGGER_DOCKER=1
TEST_EXECUTION_UT_DOCKER=1
TEST_EXECUTION_FT_DOCKER=1
GITSYNC_DOCKER=1
IMAGECREATION_DOCKER=1
APPLICATION_DEPLOYMENT=1

jobList=[GERRIT_TRIGGER_DOCKER,TEST_EXECUTION_UT_DOCKER,TEST_EXECUTION_FT_DOCKER,GITSYNC_DOCKER,IMAGECREATION_DOCKER,APPLICATION_DEPLOYMENT]

#xml file names of the jobs - should be same as the xml files stored in the jobs folder
jobNameList=["1.GERRIT_TRIGGER_DOCKER","2.TEST_EXECUTION_UT_DOCKER","3.TEST_EXECUTION_FT_DOCKER","4.GITSYNC_DOCKER", "5.IMAGECREATION_DOCKER","6.APPLICATION_DEPLOYMENT"]

